memoryManagement.h
START
SIZE
SIZE8
Referenced by check_for_space, memory_free, memory_size.
SIZE16
Referenced by check_for_space, memory_free, memory_size.
SIZE32
Referenced by check_for_space, memory_free, memory_size.
SIZE64
Referenced by check_for_space, memory_free, memory_size.
SIZE128
Referenced by check_for_space, memory_free, memory_size.
SIZE256
Referenced by check_for_space, memory_free, memory_size.
SIZE512
Referenced by check_for_space, memory_free, memory_size.
SIZE1024
Referenced by check_for_space, memory_free, memory_size.
SIZE2048
Referenced by check_for_space, memory_free, memory_size.
ALL
TOTAL_BLOCKS_OF_SIZE_SIZE8
TOTAL_BLOCKS_OF_SIZE_SIZE16
TOTAL_BLOCKS_OF_SIZE_SIZE32
TOTAL_BLOCKS_OF_SIZE_SIZE64
TOTAL_BLOCKS_OF_SIZE_SIZE128
TOTAL_BLOCKS_OF_SIZE_SIZE256
TOTAL_BLOCKS_OF_SIZE_SIZE512
TOTAL_BLOCKS_OF_SIZE_SIZE1024
TOTAL_BLOCKS_OF_SIZE_SIZE2048
TOTAL_BLOCKS
TOTAL_BYTES
BIT_AREA_MIN
START_LENGTH_SIZE8
Referenced by check_for_space, memory_free, used_blocks, unused_blocks.
END_LENGTH_SIZE8
Referenced by check_for_space, used_blocks, unused_blocks.
START_LENGTH_SIZE16
Referenced by check_for_space, memory_free, used_blocks, unused_blocks.
END_LENGTH_SIZE16
Referenced by check_for_space, used_blocks, unused_blocks.
START_LENGTH_SIZE32
Referenced by check_for_space, memory_free, used_blocks, unused_blocks.
END_LENGTH_SIZE32
Referenced by check_for_space, used_blocks, unused_blocks.
START_LENGTH_SIZE64
Referenced by check_for_space, memory_free, used_blocks, unused_blocks.
END_LENGTH_SIZE64
Referenced by check_for_space, used_blocks, unused_blocks.
START_LENGTH_SIZE128
Referenced by check_for_space, memory_free, used_blocks, unused_blocks.
END_LENGTH_SIZE128
Referenced by check_for_space, used_blocks, unused_blocks.
START_LENGTH_SIZE256
Referenced by check_for_space, memory_free, used_blocks, unused_blocks.
END_LENGTH_SIZE256
Referenced by check_for_space, used_blocks, unused_blocks.
START_LENGTH_SIZE512
Referenced by check_for_space, memory_free, used_blocks, unused_blocks.
END_LENGTH_SIZE512
Referenced by check_for_space, used_blocks, unused_blocks.
START_LENGTH_SIZE1024
Referenced by check_for_space, memory_free, used_blocks, unused_blocks.
END_LENGTH_SIZE1024
Referenced by check_for_space, used_blocks, unused_blocks.
START_LENGTH_SIZE2048
Referenced by check_for_space, memory_free, used_blocks, unused_blocks.
END_LENGTH_SIZE2048
Referenced by check_for_space, used_blocks, unused_blocks.
BIT_AREA_MAX
INITIAL_LENGTH_SIZE8
Referenced by check_for_space, memory_free, memory_size.
MAX_LENGTH_SIZE8
Referenced by memory_free, memory_size.
INITIAL_LENGTH_SIZE16
Referenced by check_for_space, memory_free, memory_size.
MAX_LENGTH_SIZE16
Referenced by memory_free, memory_size.
INITIAL_LENGTH_SIZE32
Referenced by check_for_space, memory_free, memory_size.
MAX_LENGTH_SIZE32
Referenced by memory_free, memory_size.
INITIAL_LENGTH_SIZE64
Referenced by check_for_space, memory_free, memory_size.
MAX_LENGTH_SIZE64
Referenced by memory_free, memory_size.
INITIAL_LENGTH_SIZE128
Referenced by check_for_space, memory_free, memory_size.
MAX_LENGTH_SIZE128
Referenced by memory_free, memory_size.
INITIAL_LENGTH_SIZE256
Referenced by check_for_space, memory_free, memory_size.
MAX_LENGTH_SIZE256
Referenced by memory_free, memory_size.
INITIAL_LENGTH_SIZE512
Referenced by check_for_space, memory_free, memory_size.
MAX_LENGTH_SIZE512
Referenced by memory_free, memory_size.
INITIAL_LENGTH_SIZE1024
Referenced by check_for_space, memory_free, memory_size.
MAX_LENGTH_SIZE1024
Referenced by memory_free, memory_size.
INITIAL_LENGTH_SIZE2048
Referenced by check_for_space, memory_free, memory_size.
MAX_LENGTH_SIZE2048
Referenced by memory_free, memory_size.
INITIAL_LENGTH_REMAINING
MAX_LENGTH
status
unsigned char totalMemoryArea[1024 *1024 *SIZE][1024 *1024 *SIZE]
void* check_for_space(int size)
References FALSE, SIZE8, perform_alloc, START_LENGTH_SIZE8, END_LENGTH_SIZE8, INITIAL_LENGTH_SIZE8, TRUE, SIZE16, START_LENGTH_SIZE16, END_LENGTH_SIZE16, INITIAL_LENGTH_SIZE16, SIZE32, START_LENGTH_SIZE32, END_LENGTH_SIZE32, INITIAL_LENGTH_SIZE32, SIZE64, START_LENGTH_SIZE64, END_LENGTH_SIZE64, INITIAL_LENGTH_SIZE64, SIZE128, START_LENGTH_SIZE128, END_LENGTH_SIZE128, INITIAL_LENGTH_SIZE128, SIZE256, START_LENGTH_SIZE256, END_LENGTH_SIZE256, INITIAL_LENGTH_SIZE256, SIZE512, START_LENGTH_SIZE512, END_LENGTH_SIZE512, INITIAL_LENGTH_SIZE512, SIZE1024, START_LENGTH_SIZE1024, END_LENGTH_SIZE1024, INITIAL_LENGTH_SIZE1024, SIZE2048, START_LENGTH_SIZE2048, END_LENGTH_SIZE2048, INITIAL_LENGTH_SIZE2048.
Referenced by memory_alloc.
void* memory_alloc(int size)
References check_for_space.
Referenced by memory_calloc, memory_realloc, main.
void* memory_calloc(int nelem, int elsize)
References memory_alloc.
Referenced by main.
void* memory_realloc(void *ptr, int size)
References memory_alloc, memory_size, memory_free.
Referenced by main.
int memory_size(void *ptr)
References INITIAL_LENGTH_SIZE8, MAX_LENGTH_SIZE8, SIZE8, INITIAL_LENGTH_SIZE16, MAX_LENGTH_SIZE16, SIZE16, INITIAL_LENGTH_SIZE32, MAX_LENGTH_SIZE32, SIZE32, INITIAL_LENGTH_SIZE64, MAX_LENGTH_SIZE64, SIZE64, INITIAL_LENGTH_SIZE128, MAX_LENGTH_SIZE128, SIZE128, INITIAL_LENGTH_SIZE256, MAX_LENGTH_SIZE256, SIZE256, INITIAL_LENGTH_SIZE512, MAX_LENGTH_SIZE512, SIZE512, INITIAL_LENGTH_SIZE1024, MAX_LENGTH_SIZE1024, SIZE1024, INITIAL_LENGTH_SIZE2048, MAX_LENGTH_SIZE2048, SIZE2048.
Referenced by memory_realloc.
int used_blocks(int size)
References calculate_blocks, START_LENGTH_SIZE8, END_LENGTH_SIZE8, START_LENGTH_SIZE16, END_LENGTH_SIZE16, START_LENGTH_SIZE32, END_LENGTH_SIZE32, START_LENGTH_SIZE64, END_LENGTH_SIZE64, START_LENGTH_SIZE128, END_LENGTH_SIZE128, START_LENGTH_SIZE256, END_LENGTH_SIZE256, START_LENGTH_SIZE512, END_LENGTH_SIZE512, START_LENGTH_SIZE1024, END_LENGTH_SIZE1024, START_LENGTH_SIZE2048, END_LENGTH_SIZE2048.
Referenced by block_information.
int unused_blocks(int size)
References calculate_free_blocks, START_LENGTH_SIZE8, END_LENGTH_SIZE8, START_LENGTH_SIZE16, END_LENGTH_SIZE16, START_LENGTH_SIZE32, END_LENGTH_SIZE32, START_LENGTH_SIZE64, END_LENGTH_SIZE64, START_LENGTH_SIZE128, END_LENGTH_SIZE128, START_LENGTH_SIZE256, END_LENGTH_SIZE256, START_LENGTH_SIZE512, END_LENGTH_SIZE512, START_LENGTH_SIZE1024, END_LENGTH_SIZE1024, START_LENGTH_SIZE2048, END_LENGTH_SIZE2048.
Referenced by block_information.
int perform_alloc(int minimum, int maximum, int start, int size)
Referenced by check_for_space.
int calculate_blocks(int minimum, int maximum)
Referenced by used_blocks.
int calculate_free_blocks(int minimum, int maximum)
Referenced by unused_blocks.
status memory_free(void *pointer)
References FALSE, INITIAL_LENGTH_SIZE8, MAX_LENGTH_SIZE8, delete_pointer, START_LENGTH_SIZE8, SIZE8, INITIAL_LENGTH_SIZE16, MAX_LENGTH_SIZE16, START_LENGTH_SIZE16, SIZE16, INITIAL_LENGTH_SIZE32, MAX_LENGTH_SIZE32, START_LENGTH_SIZE32, SIZE32, INITIAL_LENGTH_SIZE64, MAX_LENGTH_SIZE64, START_LENGTH_SIZE64, SIZE64, INITIAL_LENGTH_SIZE128, MAX_LENGTH_SIZE128, START_LENGTH_SIZE128, SIZE128, INITIAL_LENGTH_SIZE256, MAX_LENGTH_SIZE256, START_LENGTH_SIZE256, SIZE256, INITIAL_LENGTH_SIZE512, MAX_LENGTH_SIZE512, START_LENGTH_SIZE512, SIZE512, INITIAL_LENGTH_SIZE1024, MAX_LENGTH_SIZE1024, START_LENGTH_SIZE1024, SIZE1024, INITIAL_LENGTH_SIZE2048, MAX_LENGTH_SIZE2048, START_LENGTH_SIZE2048, SIZE2048.
Referenced by memory_realloc, main.
status delete_pointer(int minimum, int start, int size, void *ptr)
References TRUE.
Referenced by memory_free.
status block_information(void)
References used_blocks, unused_blocks, TRUE.
Referenced by main.
status free_block_information(void)