.TH "src/user.c" 3 "Thu Oct 1 2015" "Version version2" "MEMORY MANAGEMENT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/user.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'memoryManagement\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBERR_NO_NUM\fP   -1"
.br
.ti -1c
.RI "#define \fBERR_NO_MEM\fP   -2"
.br
.ti -1c
.RI "#define \fBMAX_SIZE\fP   8000"
.br
.ti -1c
.RI "#define \fBMALLOC_MAX_SIZE\fP   2048"
.br
.ti -1c
.RI "#define \fBCALLOC_MAX_SIZE\fP   50"
.br
.ti -1c
.RI "#define \fBCALLOC_MAX_ELEMENTS\fP   20"
.br
.ti -1c
.RI "#define \fBREALLOC_MAX_SIZE\fP   2048"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmyRandom\fP (int size)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CALLOC_MAX_ELEMENTS   20"

.SS "#define CALLOC_MAX_SIZE   50"

.SS "#define ERR_NO_MEM   -2"

.SS "#define ERR_NO_NUM   -1"

.SS "#define MALLOC_MAX_SIZE   2048"

.SS "#define MAX_SIZE   8000"

.SS "#define REALLOC_MAX_SIZE   2048"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SS "int myRandom (int size)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MEMORY MANAGEMENT from the source code\&.
